### ISSUE TITLE
Ansible floating IPs seem to not always work 

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [RIT-GCI/code-red#5]
They bind to the instance but it's not accessible over SSH, more testing is required. (this issue is intermittent)

**Comment by ashim-mahara** [comment]
It is probably due to the lack of firewall rules allowing internal access and router routes. I'll look into it next time I'm working. I advise you to work on the instance with a network unattached to the router for now (check if it works).

**Comment by gidoBOSSftw5731** [comment]
Issue had to do with double-gateways, easy enough to solve by just adding a network to the router and using only one port.
