### ISSUE TITLE
Create instances for each subnet and attach them to the appropriate subnet

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [RIT-GCI/code-red#7]
~Subnets should already exist in terraform, No instances on some subnets as of now.~
~-Gideon, 2023-10-17~

- [ ] DC Server - Microsoft 16/19 -> Enterprise LAN 
- [ ] Application Server - Microsoft 16/19 -> Business Lan
- [ ] Nuclear Control Server - Unix/Linux/IBM - > Control System LAN
 
Could add more, depending on scope vs time.

![image](https://github.com/RIT-GCI/code-red/assets/48154590/b3571f0c-988f-49b9-b600-fd6308c9e841)

**Comment by gidoBOSSftw5731** [comment]
Instances exist, @ashim-mahara if they look good to you then this can be closed.

**Comment by ashim-mahara** [comment]
@gidoBOSSftw5731
