### ISSUE TITLE
Add users for us via ansible with ssh keys

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [RIT-GCI/code-red#9]

**Comment by gidoBOSSftw5731** [comment]
@ashim-mahara Once you add your SSH key to ssh_keys/id_ashim.pub and a hashed password to playbooks/generateusers.yml, you should be able to log in to any machine with ashim@1.2.3.4.

**Comment by ashim-mahara** [comment]
@gidoBOSSftw5731 please mention the commits here or create a PR request for me to review. you can link commits with issues by using "#{issue_number}" in the commit message.

**Comment by ashim-mahara** [comment]
Closing as this is resolved. I'll add my pub key to it the push it.
